# Controls what gets printed to console
# Valid levels are: OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL
# Generally, for testing, you might set Print_Level: FINEST to get more information
# A dev might ask you to set Stack_Traces_Level: WARNING to get information
# Alerts are used to warn admins in game when an error occurs... you can set that to OFF or SEVERE to limit alerts
Logger_Config:
  Print_Level: "CONFIG"
  Stack_Traces_Level: "OFF"
  Alert_Level: "WARNING"
  Max_Alerts_To_Show: 5
  Alert_Interval: 300  # 15 seconds * 20 ticks per second

# Turning on this feature will cause placeholder messages to use 3x the CPU.
# If you want to use "placeholders inside of placeholders," like:
# %changeoutput<_input:<ammo_left>_matcher:10_ifmatch:<ammo_left>_else:0<ammo_left>%,
# then you need to set this to true.
Advanced_Placeholders: false

# The MechanicsCore item registry is *very* primitive. Imagine you have 'steel'
# and 'steel_sheet' as 2 custom items. When MechanicsCore first loads,
# 'steel_sheet' will actually be broken since 'steel' doesn't exist yet. To fix
# this, we loop a few times until no errors occur. If you have a *highly
# complex* crafting system, then you may want to raise this number. You should
# never need to lower it.
Item_Loop_Limit: 10

# When a mistake is found in config, how many options do we print?
# Bigger numbers = more information
# Smaller numbers = tidier console
Show_Serialize_Options: 32